#pragma once

enum EParams
{
  // EFFECTS
  kParamChorusPhase,
  kParamChorusRate,
  kParamChorusDepth,
  kParamChorusFeedback,
  kParamChorusWet,
  
  kParamDelayTimeLMS,
  kParamDelayTimeRMS,
  kParamDelayTimeLBPM,
  kParamDelayTimeRBPM,
  kParamDelayFeedbackLeft,
  kParamDelayHidampLeft,
  kParamDelayLevelLeft,
  kParamDelayFeedbackRight,
  kParamDelayHidampRight,
  kParamDelayLevelRight,
  kParamDelayWet,
  
  kParamFlangerChorus,
  kParamEffectBypass,
  kParamDelayUnitLeft,
  kParamDelayUnitRight,
  kParamDelayCrossDual,
  
  kParamMidiClockBpm,
  kParamUserFactory,
  
  // MIXER UI
  kParamMixerDrive,
  kParamMixerBass,
  kParamMixerTreble,
  kParamMixerBalance,
  kParamMixerLevel,
  kParamLAIGain,
  kParamLAIBass,
  kParamLAITreble,
  kParamLAIPan,
  kParamLAILevel,
  kParamRAIGain,
  kParamRAIBass,
  kParamRAITreble,
  kParamRAIPan,
  kParamRAILevel,
  kParamMixerLink,
  kParamKeyboardOctave,
  kParamProgram,

  kParamBassSynthGlide,
  kParamBassSynthFine,
  kParamBassSynthFormant,
  kParamBassSynthDrive,
  kParamBassSynthQ,
  kParamBassSynthEnvAmt,
  kParamBassSynthFilterMod,
  kParamBassSynthTracking,
  kParamBassSynthRetrig,
  kParamBassSynthCoarse,
  kParamBassSynthCutoff,
  kParamBassSynthRate,
  kParamBassSynthFilterEnvAttack,
  kParamBassSynthFilterEnvDecay,
  kParamBassSynthAmpEnvAttack, 
  kParamBassSynthAmpEnvDecay, 
  kParamBassSynthAmpEnvRelease,

  kParamBassdrum1BodyImpact,
  kParamBassdrum1BodyTime,
  kParamBassdrum1TransientImpact,
  kParamBassdrum1TransientTime,
  kParamBassdrum1SynthTune,
  kParamBassdrum1BodyPunchSnapNormal,
  kParamBassdrum1TransientPunchSnapNormal,
  kParamBassdrum1Waveform,
  kParamBassdrum1AmpEnvAttack, 
  kParamBassdrum1AmpEnvDecay, 
  kParamBassdrum1AmpEnvRelease,
  kParamBassdrum1AmpEnvCurve,

  kParamBassdrum2BodyImpact,
  kParamBassdrum2BodyTime,
  kParamBassdrum2TransientImpact,
  kParamBassdrum2TransientTime,
  kParamBassdrum2SynthTune,
  kParamBassdrum2BodyPunchSnapNormal,
  kParamBassdrum2TransientPunchSnapNormal,
  kParamBassdrum2Waveform,
  kParamBassdrum2AmpEnvAttack,
  kParamBassdrum2AmpEnvDecay,
  kParamBassdrum2AmpEnvRelease,
  kParamBassdrum2AmpEnvCurve,

  kParamCabasaQ,
  kParamCabasaColor,
  kParamCabasaAttack,
  kParamCabasaDecay,

  kParamClapPeople,
  kParamClapQ,
  kParamClapColor,
  kParamClapDecay,

  kParamCowbellFM,
  kParamCowbellTonality,
  kParamCowbellTune,
  kParamCowbellDecay,
  kParamCowbellWaveform,

  kParamCymbalSwell,
  kParamCymbalDefinition,
  kParamCymbalTune,
  kParamCymbalColor,
  kParamCymbalDecay,
  kParamCymbalWaveform,

  kParamHihatType,
  kParamHihatQ,
  kParamHihatColor,
  kParamHihatClosed,
  kParamHihatOpen,

  kParamSnaredrum1Impact,
  kParamSnaredrum1Time,
  kParamSnaredrum1Q,
  kParamSnaredrum1Tune,
  kParamSnaredrum1Color,
  kParamSnaredrum1BodySnares,
  kParamSnaredrum1Tightness,
  kParamSnaredrum1Waveform,
  kParamSnaredrum1Decay,

  kParamSnaredrum2Impact,
  kParamSnaredrum2Time,
  kParamSnaredrum2Q,
  kParamSnaredrum2Tune,
  kParamSnaredrum2Color,
  kParamSnaredrum2BodySnares,
  kParamSnaredrum2Tightness,
  kParamSnaredrum2Waveform,
  kParamSnaredrum2Decay,

  kParamTom1Impact,
  kParamTom1Time,
  kParamTom1NoiseLevel,
  kParamTom1Tune,
  kParamTom1NoiseColor,
  kParamTom1Waveform,
  kParamTom1NoiseDecay,

  kParamTom2Impact,
  kParamTom2Time,
  kParamTom2NoiseLevel,
  kParamTom2Tune,
  kParamTom2NoiseColor,
  kParamTom2Waveform,
  kParamTom2NoiseDecay,

  kParamEffectsFilterQ,
  kParamEffectsFilterEnvelope,
  kParamEffectsDriveTone,
  kParamEffectsChorusOffset,
  kParamEffectsChorusFeedback,
  kParamEffectsDelayDamp,
  kParamEffectsDelayFeedback,
  kParamEffectsFilterCutoff,
  kParamEffectsDriveAmount,
  kParamEffectsChorusRate,
  kParamEffectsChorusDepth,
  kParamEffectsDelayTimeL,
  kParamEffectsDelayTimeR,
  kParamEffectsFilterType,
  kParamEffectsFilterMute,
  kParamEffectsDriveMute,
  kParamEffectsChorusMute,
  kParamEffectsDelayMute,

  // MIXER EFFECT

  kParamMixerDelayBD1,
  kParamMixerDelayBD2,
  kParamMixerDelaySD1,
  kParamMixerDelaySD2,
  kParamMixerDelayTO1,
  kParamMixerDelayTO2,
  kParamMixerDelayHH,
  kParamMixerDelayCY,
  kParamMixerDelayCow,
  kParamMixerDelayCL,
  kParamMixerDelayCB,
  kParamMixerDelayBass,
  
  kParamMixerChorusBD1,
  kParamMixerChorusBD2,
  kParamMixerChorusSD1,
  kParamMixerChorusSD2,
  kParamMixerChorusTO1,
  kParamMixerChorusTO2,
  kParamMixerChorusHH,
  kParamMixerChorusCY,
  kParamMixerChorusCow,
  kParamMixerChorusCL,
  kParamMixerChorusCB,
  kParamMixerChorusBass,
  
  kParamMixerPanBD1,
  kParamMixerPanBD2,
  kParamMixerPanSD1,
  kParamMixerPanSD2,
  kParamMixerPanTO1,
  kParamMixerPanTO2,
  kParamMixerPanHH,
  kParamMixerPanCY,
  kParamMixerPanCow,
  kParamMixerPanCL,
  kParamMixerPanCB,
  kParamMixerPanBass,
  
  kParamMixerLevelBD1,
  kParamMixerLevelBD2,
  kParamMixerLevelSD1,
  kParamMixerLevelSD2,
  kParamMixerLevelTO1,
  kParamMixerLevelTO2,
  kParamMixerLevelHH,
  kParamMixerLevelCY,
  kParamMixerLevelCow,
  kParamMixerLevelCL,
  kParamMixerLevelCB,
  kParamMixerLevelBass,
  
  kParamMixerDelayReturn,
  kParamMixerChorusReturn,

  kNumParams
};
