#pragma once

enum EParams
{
  #include "../MPA Code/CommonParamEnum.h" 
  
  kParamOsc1Waveform,
  kParamOsc1Coarse,
  kParamOsc1Fine,
  kParamOsc1Grunge,
  kParamOsc1PitchModSrc,
  kParamOsc1PitchModAmt,
  kParamOsc2Waveform,
  kParamOsc2Coarse,
  kParamOsc2Fine,
  kParamOsc2Grunge,
  kParamOsc2PitchModSrc,
  kParamOsc2PitchModAmt,

  kParamMixOsc1,
  kParamMixOsc1AmpModSrc,
  kParamMixOsc1AmpModAmt,
  kParamMixOsc1Balance,
  kParamMixOsc1BalanceModSrc,
  kParamMixOsc1BalanceModAmt,
  kParamMixOsc2,
  kParamMixOsc2AmpModSrc,
  kParamMixOsc2AmpModAmt,
  kParamMixOsc2Balance,
  kParamMixOsc2BalanceModSrc,
  kParamMixOsc2BalanceModAmt,
  kParamMixGain,

  kParamVcf1Cf,
  kParamVcf1Res,
  kParamVcf1keyf,
  kParamVcf1Env,
  kParamVcf1Type,
  kParamVcf1ModCfAmt,
  kParamVcf1ModResAmt,
  kParamVcf1ModCfSrc,
  kParamVcf1ModResSrc,

  kParamVcf2Cf,
  kParamVcf2Res,
  kParamVcf2keyf,
  kParamVcf2Env,
  kParamVcf2Type,
  kParamVcf2ModCfAmt,
  kParamVcf2ModResAmt,
  kParamVcf2ModCfSrc,
  kParamVcf2ModResSrc,

  kParamVcfSerPar,
  kParamVcfLink,
  kParamVcfCutoffModSrc,
  kParamVcfCutoffModAmt,
  kParamVcfResModSrc,
  kParamVcfResModAmt,

  kParamVcfEnvTKf,
  kParamVcfEnvTVel,
  kParamVcfEnvLVel,
  kParamVcfEnvA,
  kParamVcfEnvD,
  kParamVcfEnvS,
  kParamVcfEnvR,

  kParamAmpVol,
  kParamAmpPan,
  kParamAmpPanModSrc,
  kParamAmpPanModAmt,
  kParamAmpPan1,
  kParamAmpPanModSrc1,
  kParamAmpPanModAmt1,

  kParamAmpEnvTKf,
  kParamAmpEnvTVel,
  kParamAmpEnvLVel,
  kParamAmpEnvA,
  kParamAmpEnvD,
  kParamAmpEnvS,
  kParamAmpEnvR,

  // add
  kParamCoarse,
  kParamFine,
  kParamBendRange,
  kParamPModAmt,
  kParamPModSrc,

  kParamLfo1Wave,
  kParamLfo1Rate,
  kParamLfo1RateBPM,
  kParamLfo1Retrig,
  kParamLfo1Del,
  kParamLfo1Fin,
  kParamLfo1Fout,
  kParamLfo1Midi,
  kParamLfo1Phase,
  kParamLfo1Keyf,
  kParamLfo1Rmod1Amt,
  kParamLfo1Rmod2Amt,
  kParamLfo1Rmod1Src,
  kParamLfo1Rmod2Src,
  //kParamLfo1LevModAmt,
  //kParamLfo1LevModSrc,

  kParamLfo2Wave,
  kParamLfo2Rate,
  kParamLfo2RateBPM,
  kParamLfo2Retrig,
  kParamLfo2Del,
  kParamLfo2Fin,
  kParamLfo2Fout,
  kParamLfo2Midi,
  kParamLfo2Phase,
  kParamLfo2Keyf,
  kParamLfo2Rmod1Amt,
  kParamLfo2Rmod2Amt,
  kParamLfo2Rmod1Src,
  kParamLfo2Rmod2Src,
  kParamLfo2LevModAmt,
  kParamLfo2LevModSrc,

  kParamFreeEnvTKf,
  kParamFreeEnvTVel,
  kParamFreeEnvLVel,
  kParamFreeEnvA,
  kParamFreeEnvD,
  kParamFreeEnvS,
  kParamFreeEnvR,
  kParamFreeEnvAI,
  kParamFreeEnvDR,

  kParamPitchWheel,

  kNumParams
};
