#pragma once

enum EParams
{
  // EFFECTS
  kParamChorusPhase,
  kParamChorusRate,
  kParamChorusDepth,
  kParamChorusFeedback,
  kParamChorusWet,
  
  kParamDelayTimeLMS,
  kParamDelayTimeRMS,
  kParamDelayTimeLBPM,
  kParamDelayTimeRBPM,
  kParamDelayFeedbackLeft,
  kParamDelayHidampLeft,
  kParamDelayLevelLeft,
  kParamDelayFeedbackRight,
  kParamDelayHidampRight,
  kParamDelayLevelRight,
  kParamDelayWet,
  
  kParamFlangerChorus,
  kParamEffectBypass,
  kParamDelayUnitLeft,
  kParamDelayUnitRight,
  kParamDelayCrossDual,
  
  kParamMidiClockBpm,
  kParamUserFactory,
  
  // MIXER UI
  kParamMixerDrive,
  kParamMixerBass,
  kParamMixerTreble,
  kParamMixerBalance,
  kParamMixerLevel,
  kParamLAIGain,
  kParamLAIBass,
  kParamLAITreble,
  kParamLAIPan,
  kParamLAILevel,
  kParamRAIGain,
  kParamRAIBass,
  kParamRAITreble,
  kParamRAIPan,
  kParamRAILevel,
  kParamMixerLink,
  kParamKeyboardOctave,
  kParamProgram,

  kParamTune,
  kParamVolume,
  kParamPWheel,
  kParamEnvTime,
  kParamGlide,

  kParamEffectsFeedback,
  kParamEffectsDryWet,
  kParamEffectsStereo,
  kParamEffectsDetune,

  kParamGlobalFMModEnvAmt,
  kParamGlobalFMLFOAmt,
  kParamGlobalFBModEnvAmt,
  kParamGlobalFBLFOAmt,

  kParamLfoPhase,
  kParamLfoFadeIn,

  kParamEffectsDelayTime,
  kParamFMDepth,
  kParamFeedback,
  kParamLfoFrequency,

  kParamCoarse,
  kParamOperator1Coarse,
  kParamOperator2Coarse,
  kParamOperator3Coarse,
  kParamOperator4Coarse,

  kParamModEnvAttack,
  kParamModEnvDecay,
  kParamModEnvSustain,
  kParamModEnvRelease,

  kParamOperator1Level,
  kParamOperator2Level,
  kParamOperator3Level,
  kParamOperator4Level,

  kParamOperator1Invert,
  kParamOperator2Invert,
  kParamOperator3Invert,
  kParamOperator4Invert,

  kParamLfoWaveform,
  kParamAlgorithm,

  kParamOperator1Overtone,
  kParamOperator1FMDepth,
  kParamOperator1Phase,
  kParamOperator1Feedback,
  kParamOperator1PitchLFO,
  kParamOperator1LevelLFO,
  kParamOperator1LevelVelocity,
  kParamOperator1LevelKeyf,
  kParamOperator1EnvAttack,
  kParamOperator1EnvDecay, 
  kParamOperator1EnvSustain,
  kParamOperator1EnvRelease,
  kParamOperator1EnvCurve,
  kParamOperator1Detune,
  kParamOperator1Waveform,

  kParamOperator2Overtone,
  kParamOperator2FMDepth,
  kParamOperator2Phase,
  kParamOperator2Feedback,
  kParamOperator2PitchLFO,
  kParamOperator2LevelLFO,
  kParamOperator2LevelVelocity,
  kParamOperator2LevelKeyf,
  kParamOperator2EnvAttack,
  kParamOperator2EnvDecay,
  kParamOperator2EnvSustain,
  kParamOperator2EnvRelease,
  kParamOperator2EnvCurve,
  kParamOperator2Detune,
  kParamOperator2Waveform,

  kParamOperator3Overtone,
  kParamOperator3FMDepth,
  kParamOperator3Phase,
  kParamOperator3Feedback,
  kParamOperator3PitchLFO,
  kParamOperator3LevelLFO,
  kParamOperator3LevelVelocity,
  kParamOperator3LevelKeyf,
  kParamOperator3EnvAttack,
  kParamOperator3EnvDecay,
  kParamOperator3EnvSustain,
  kParamOperator3EnvRelease,
  kParamOperator3EnvCurve,
  kParamOperator3Detune,
  kParamOperator3Waveform,

  kParamOperator4Overtone,
  kParamOperator4FMDepth,
  kParamOperator4Phase,
  kParamOperator4Feedback,
  kParamOperator4PitchLFO,
  kParamOperator4LevelLFO,
  kParamOperator4LevelVelocity,
  kParamOperator4LevelKeyf,
  kParamOperator4EnvAttack,
  kParamOperator4EnvDecay,
  kParamOperator4EnvSustain,
  kParamOperator4EnvRelease,
  kParamOperator4EnvCurve,
  kParamOperator4Detune,
  kParamOperator4Waveform,
  
  kNumParams
};
