#pragma once
enum EParams
{

  kParamMasterVolume,
  kParamSynthMic,
  kParamBoost,

kParamFilterEnv,
kParamOSCB,
kParamOSCAFreq,
kParamOSCAPW,
kParamOSCBFreq,
kParamOSCBFine,
kParamOSCBPW,
kParamSourceMix,
kParamGlide,
kParamLFOFreq,
kParamMixOSCA,
kParamMixOSCB,
kParamMixNoise,
kParamMasterTune,
kParamVCFCutoff,
kParamVCFResonance,
kParamVCFEnvAmt,
kParamVCFKybAmt,
kParamVCFAttack,
kParamVCFDecay,
kParamVCFSustain,
kParamVCFRelease,
kParamVCFVelocity,
kParamVCAAttack,
kParamVCADecay,
kParamVCASustain,
kParamVCARelease,
kParamVCAVelocity,
kParamVolume,

kParamMWIntensity,
kParamMWOffset,
kParamMWBendRange,
kParamVoices,
kParamDetune,
kParamATPitch,
kParamATPw,
kParamATFIlter,
kParamATAmp,
kParamATMWAmt,
kParamATLfoFreq,
kParamTimeVelVCFAttack,
kParamTimeVelVCFDecrel,
kParamTimeVelVCAAttack,
kParamTimeVelVCADecrel,
kParamLFOPhase,

kParamChorusRate,
kParamChorusPhase,
kParamChorusDepth,
kParamChorusFB,
kParamChorusMix,
kParamDelayTimeL,
kParamDelayTimeR,

kParamDelayUnitL,
kParamDelayUnitR,
kParamDelayFBL,
kParamDelayFBR,
kParamDelayHidampL,
kParamDelayHidampR,
kParamDelayLevelL,
kParamDelayLevelR,
kParamDelayMix,


kParamPolymodFRQA,
kParamPolymodFRQB,
kParamPolymodPWA,
kParamPolymodPWB,
kParamPolymodFilter,
kParamWheelmodFRQA,
kParamWheelmodFRQB,
kParamWheelmodPWA,
kParamWheelmodPWB,
kParamWheelmodFilter,
kParamOSCASaw,
kParamOSCAPulse,
kParamOSCASync,
kParamOSCBSaw,
kParamOSCBPulse,
kParamOSCBTri,
kParamOSCBLowFreq,
kParamOSCBKeyb,
kParamLFOSaw,
kParamLFOTri,
kParamLFOPulse,
kParamAdr,
kParamRelease,


kParamKybRetrig,
kParamKybLowNote,
kParamKybSingle,
kParamAtFreqA,
kParamAtFreqB,
kParamAtPwA,
kParamAtPwB,
kParamLfoRetrig,
kParamLfoMidi,


kParamFlanger,
kParamDelayBpmL,
kParamDelayBpmR,
kParamDelayCross,
kParamEffectBypass,

kParamUnison,
kParamMidiBpm,

kParamKeyboardOctave,
kParamProgram,
kParamMidiActive,

kParamPitchWheel,

  kNumParams
};
