#pragma once

  kCtrlTagKeyboard,
  kCtrlTagKeybHide,
  kCtrlTagMidiMonHide,
  kCtrlTagMidiBack,
  kCtrlTagClear,
  kCtrlTagPresetMenu,
  kCtrlTagDelayTimeLMS,
  kCtrlTagDelayTimeRMS,
  kCtrlTagDelayTimeLBPM,
  kCtrlTagDelayTimeRBPM,
  
  kCtrlSave,
  kCtrlLoad,
  kCtrlProgram,
  
  kCtrlTagMidiLogger,
  kCtrlTagPresetList,
  kCtrlSliderMidiMon1,
  kCtrlSliderPresetList,
  
  kCtrlTagMixerHide,
  kCtrlMixerLink,
  kCtrlRAIGain,
  kCtrlRAIBass,
  kCtrlRAITreble,
  kCtrlRAILevel,
  kCtrlLAIPan,
  kCtrlRAIPan,
  kCtrlLAIGain,
  kCtrlLAIBass,
  kCtrlLAITreble,
  kCtrlLAILevel,

  kCtrlMidiActive,
  kCtrlUserFactory,